name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Prepare .env file
        run: cp .env.example .env

      - name: Build backend
        run: docker compose build backend

      - name: Run test
        run: docker compose run --rm backend pytest

      - name: Stop container
        if: always()
        run: docker compose down -v